spring:
  flyway:
    locations: classpath:dbmigration
    enabled: true
  batch:
    jdbc:
      initialize-schema: always
    # set batch false in integration test and run batch manually with batch runner to set dynamic test property values
    # eg. dynamic properties ${parent.file.name}
    job:
      enabled: false
  main:
    allow-circular-references: true

#Local integration testing these values should be actual
#ACCOUNT_NAME: ${ACCOUNT_NAME}
#ACCOUNT_KEY: ${ACCOUNT_KEY}
commondata-flag-details-start-route: direct:CommonData-FlagDetails
commondata-flag-service-start-route: direct:CommonData-FlagService
commondata-categories-start-route: direct:CommonData-ListOfValues
commondata-caselinking-start-route: direct:CommonData-CaseLinkingReasons
commondata-othercategories-start-route: direct:CommonData-OtherCategories
archival-route: direct:CommonDataArchival
archival-path: azure-blob://${azure.storage.account-name}/rd-common-data-archive
active-blob-path: azure-blob://${azure.storage.account-name}/rd-common-data
archival-file-names: FlagDetails-test.csv,FlagService-test.csv,ListOfValues-test.csv,CaseLinkingReasons-test.csv,OtherCategories-test.csv
archival-cred: credentials=#credsreg&operation=updateBlockBlob
#archival-date-format keep in dd-MM-yyyy as to delete in testing
archival-date-format: dd-MM-yyyy
file-read-time-out: 2000
scheduler-audit-select: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date
invalid-exception-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) values(?, ?, ?, ?, ?)
invalid-jsr-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp, row_id) values(?, ?, ?, ?, ?, ?, ?, ?)
jsr-threshold-limit: 10
batchjob-name: CommonDataLoad
scheduler-insert-sql: insert into dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) values(?,?,?,?,?)
audit-enable: true
commondata-flag-service-route-task: commonDataFlagServiceLoadTask
commondata-flag-service-routes-to-execute: commondata-flag-service-load
commondata-categories-route-task: commonDataListOfValuesLoadTask
commondata-categories-routes-to-execute: commondata-list-of-values-load
commondata-caselinking-route-task: commonDataCaseLinkingReasonsTask
commondata-caselinking-routes-to-execute: commondata-case-linking-reasons-load
commondata-flag-details-route-task: commonDataFlagDetailsLoadTask
commondata-flag-details-routes-to-execute: commondata-flag-details-load
commondata-othercategories-route-task: commonDataOtherCategoriesTask
commondata-othercategories-routes-to-execute: commondata-other-categories-load
route:
  commondata-flag-details-load:
    id: commondata-flag-details-load
    file-name: FlagDetails-test.csv
    table-name: flag_details
    truncate-sql:
      sql:truncate table flag_details restart identity cascade?dataSource=dataSource
    insert-sql:
      sql:insert into flag_details (id,flag_code,value_en,value_cy,category_id,mrd_created_time,mrd_updated_time,mrd_deleted_time)
      values(:#id,:#flag_code,:#value_en,:#value_cy,:#category_id,:#mrd_created_time,:#mrd_updated_time,:#mrd_deleted_time)?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/FlagDetails-test.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: flagDetailsProcessor
    mapper-class: flagDetailsMapper
    csv-binder-object: FlagDetails
    csv-headers-expected: id,flag_code,value_en,value_cy,category_id,MRD_Created_Time,MRD_Updated_Time,MRD_Deleted_Time
    header-validation-enabled: true
  commondata-flag-service-load:
    id: commondata-flag-service-load
    file-name: FlagService-test.csv
    table-name: flag_service
    truncate-sql:
      sql:truncate table flag_service restart identity?dataSource=dataSource
    insert-sql:
      sql:insert into flag_service (id,service_id,hearing_relevant,request_reason,flag_code,default_status,available_externally)
      values(:#id,:#service_id,:#hearing_relevant,:#request_reason,:#flag_code,:#default_status,:#available_externally)?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/FlagService-test.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: flagServiceProcessor
    mapper-class: flagServiceMapper
    csv-binder-object: FlagService
    csv-headers-expected: ID,ServiceID,HearingRelevant,RequestReason,FlagCode,DefaultStatus,AvailableExternally
    header-validation-enabled: true
  commondata-list-of-values-load:
    id: commondata-list-of-values-load
    file-name: ListOfValues-test.csv
    table-name: List_Of_Values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active,external_reference,external_reference_type)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active,:#external_reference,:#external_reference_type) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active,external_reference = :#external_reference,external_reference_type = :#external_reference_type?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/ListOfValues-test.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: listOfValuesProcessor
    mapper-class: listOfValuesMapper
    csv-binder-object: ListOfValues
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type
    header-validation-enabled: false
  commondata-case-linking-reasons-load:
    id: commondata-case-linking-reasons-load
    file-name: CaseLinkingReasons-test.csv
    table-name: List_Of_Values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/CaseLinkingReasons-test.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: listOfValuesProcessor
    mapper-class: listOfValuesMapper
    csv-binder-object: ListOfValues
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active
    header-validation-enabled: true
  commondata-other-categories-load:
    id: commondata-other-categories-load
    file-name: OtherCategories-test.csv
    table-name: List_Of_Values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active,external_reference,external_reference_type)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active,:#external_reference,:#external_reference_type) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active,external_reference = :#external_reference,external_reference_type = :#external_reference_type?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/OtherCategories-test.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: listOfValuesProcessor
    mapper-class: listOfValuesMapper
    csv-binder-object: ListOfValues
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type
    header-validation-enabled: true
exception-select-query: select * from  dataload_exception_records
ordered-exception-select-query: select * from  dataload_exception_records order by error_description
exception-records-select-query: select * from  dataload_exception_records where row_id is not null
flag-service-select-sql: select * from flag_service
list-of-values-select-sql: select * from list_of_values
flag-details-select-sql: select * from flag_details
select-dataload-scheduler: select *  from dataload_schedular_audit
flag-code-query: select flag_code from flag_details
select-dataload-scheduler-failure: select *  from dataload_schedular_audit where status='Failure'
truncate-audit: truncate dataload_schedular_audit
truncate-exception: truncate dataload_exception_records
jdbc-batch-size: 10
logging-component-name: RD_Common_Data
component:
  name: Common Reference Data
mail:
  enabled: false
idempotent-flag-ingestion: true
CONTAINER_NAME: rd-common-data
zero-byte-characters: >
  \u200B,
   

