apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rd-commondata-dataload
name: rd-commondata-dataload
home: https://github.com/hmcts/rd-commondata-dataload
version: 0.0.1
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
