job:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  global:
    jobKind: CronJob
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: dbcommondata
    POSTGRES_USERNAME: dbcommondata
    POSTGRES_PASSWORD: dbcommondata
    FLYWAY_ENABLED: true
    CONTAINER_NAME: rd-common-data
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbcommondata
  postgresqlPassword: dbcommondata
  postgresqlDatabase: dbcommondata
  persistence:
    enabled: false

blobstorage:
  resourceGroup: rd-aks-pr-test
  teamName: "RD"
  location: ukwest
  setup:
    containers:
      - rd-common-data
      - rd-common-data-archive
  enabled: true
