job:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  global:
    jobKind: CronJob
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: dbcommondata
    POSTGRES_USERNAME: dbcommondata
    POSTGRES_PASSWORD: dbcommondata
    POSTGRES_PORT: 5432
    FLYWAY_ENABLED: true
    # LOCATIONS_DB: classpath:db/migration,classpath:db/postgres,classpath:db/migrationAks
    # LAUNCH_DARKLY_ENV: "preview"
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        # - name: commondata-api-s2s-secret
        #   alias: COMMONDATA_API_S2S_SECRET

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbcommondata
  postgresqlPassword: dbcommondata
  postgresqlDatabase: dbcommondata
  postgresqlPort: 5432
  persistence:
    enabled: false
