job:
  applicationPort: 8100
  # ingressHost: rd-commondata-dataload-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  image: 'hmctspublic.azurecr.io/rd/commondata-dataload:latest'
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob

  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: commondata-api-POSTGRES-PASS
          alias: spring.datasource.password
        # - name: commondata-api-s2s-secret
        #   alias: COMMONDATA_API_S2S_SECRET

  environment:
    POSTGRES_HOST: rd-commondata-api-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: dbcommondata@rd-commondata-api-postgres-db-v11-{{ .Values.global.environment }}
    POSTGRES_DB_NAME: dbcommondata
    POSTGRES_PORT: 5432
    FLYWAY_ENABLED: false
    # S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    # OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    # OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    # IDAM_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    # LOCATIONS_DB: classpath:db/migration,classpath:db/postgres
    # LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"

postgresql:
  enabled: false
