commondata-othercategories-start-route: direct:CommonData-OtherCategories
commondata-othercategories-route-task: commonDataOtherCategoriesTask
commondata-othercategories-routes-to-execute: commondata-other-categories-load
route:
  commondata-other-categories-load:
    id: commondata-other-categories-load
    file-name: OtherCategories.csv
    table-name: list_of_values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active,external_reference,external_reference_type)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active,:#external_reference,:#external_reference_type) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active,external_reference = :#external_reference,external_reference_type = :#external_reference_type?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/OtherCategories.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: otherCategoriesProcessor
    mapper-class: otherCategoriesMapper
    csv-binder-object: otherCategories
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active,external_reference,external_reference_type
    header-validation-enabled: true
