commondata-caselinking-start-route: direct:CommonData-CaseLinkingReasons
commondata-caselinking-route-task: commonDataCaseLinkingReasonsTask
commondata-caselinking-routes-to-execute: commondata-case-linking-reasons-load
commondata-caselinking-route-disable: ${caselinking-route-disable:false}
route:
  commondata-case-linking-reasons-load:
    id: commondata-case-linking-reasons-load
    file-name: CaseLinkingReasons.csv
    table-name: list_of_values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active?dataSource=#dataSource
    blob-path:
      azure-storage-blob://${azure.storage.account-name}/rd-common-data?credentials=#credsreg&operation=uploadBlockBlob&blobName=CaseLinkingReasons.csv
    processor-class: categoriesProcessor
    mapper-class: categoriesMapper
    csv-binder-object: Categories
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active
    header-validation-enabled: true
