commondata-othercategories-start-route: direct:CommonData-OtherCategoriesReasons
commondata-othercategories-route-task: commonDataOtherCategoriesReasonsTask
commondata-othercategories-routes-to-execute: commondata-other-categories-reasons-load
route:
  commondata-other-categories-reasons-load:
    id: commondata-other-categories-reasons-load
    file-name: OtherCategories.csv
    table-name: list_of_values
    insert-sql:
      sql:insert into list_of_values (categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,
      parentcategory,parentkey,active)
      values(:#categoryKey,:#serviceId,:#key,:#value_en,:#value_cy,:#hinttext_en,:#hinttext_cy,:#lov_order,
      :#parentcategory,:#parentkey,:#active) on conflict (categorykey,key,serviceid) do UPDATE SET categorykey = :#categoryKey,
      serviceid = :#serviceId, value_en = :#value_en, value_cy = :#value_cy, hinttext_en =:#hinttext_en,
      hinttext_cy = :#hinttext_cy, lov_order = :#lov_order, parentcategory = :#parentcategory, parentkey = :#parentkey,
      active = :#active?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-common-data/OtherCategories.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: categoriesProcessor
    mapper-class: categoriesMapper
    csv-binder-object: Categories
    csv-headers-expected: categorykey,serviceid,key,value_en,value_cy,hinttext_en,hinttext_cy,lov_order,parentcategory,parentkey,active
    header-validation-enabled: true
